
export type TextureName = 
  "albedo" | 
  "ao" | 
  "avatar" | 
  "lightmap" | 
  "lightmap_hdr" | 
  "matcap_clay" | 
  "matcap_red_plastic" | 
  "matcap_white" | 
  "normal" | 
  "nx" | 
  "ny" | 
  "nz" | 
  "px" | 
  "py" | 
  "pz" | 
  "roughness" | 
  "skybox_ditch_river" | 
  "texture1" | 
  "texture2"
;


export type TexturePath = 
  "samples/room/lightmap_hdr.png" | 
  "samples/room/lightmap_hdr.png.webp" | 
  "samples/room/lightmap.jpg" | 
  "samples/room/lightmap.jpg.webp" | 
  "samples/suzanne/albedo.jpg" | 
  "samples/suzanne/ao.jpg" | 
  "samples/suzanne/normal.jpg" | 
  "samples/suzanne/roughness.jpg" | 
  "samples/textures/avatar_LOD0.png" | 
  "samples/textures/avatar_LOD1.png" | 
  "samples/textures/avatar_LOD2.png" | 
  "samples/textures/matcap_clay.jpg" | 
  "samples/textures/matcap_red_plastic.jpg" | 
  "samples/textures/matcap_white.jpg" | 
  "samples/textures/protospace/nx.jpg" | 
  "samples/textures/protospace/ny.jpg" | 
  "samples/textures/protospace/nz.jpg" | 
  "samples/textures/protospace/px.jpg" | 
  "samples/textures/protospace/py.jpg" | 
  "samples/textures/protospace/pz.jpg" | 
  "samples/textures/skybox_ditch_river.jpg" | 
  "samples/textures/texture1.jpg" | 
  "samples/textures/texture1.jpg.astc.ktx" | 
  "samples/textures/texture1.jpg.basis.ktx2" | 
  "samples/textures/texture1.jpg.dxt.ktx" | 
  "samples/textures/texture1.jpg.etc.ktx" | 
  "samples/textures/texture1.jpg.pvr.ktx" | 
  "samples/textures/texture1.jpg.webp" | 
  "samples/textures/texture2.jpg"
;


export type OtherAssetName = 
  "cubemap" | 
  "m0_nx" | 
  "m0_ny" | 
  "m0_nz" | 
  "m0_px" | 
  "m0_py" | 
  "m0_pz" | 
  "m1_nx" | 
  "m1_ny" | 
  "m1_nz" | 
  "m1_px" | 
  "m1_py" | 
  "m1_pz" | 
  "m2_nx" | 
  "m2_ny" | 
  "m2_nz" | 
  "m2_px" | 
  "m2_py" | 
  "m2_pz" | 
  "m3_nx" | 
  "m3_ny" | 
  "m3_nz" | 
  "m3_px" | 
  "m3_py" | 
  "m3_pz" | 
  "m4_nx" | 
  "m4_ny" | 
  "m4_nz" | 
  "m4_px" | 
  "m4_py" | 
  "m4_pz" | 
  "nx" | 
  "ny" | 
  "nz" | 
  "octa" | 
  "px" | 
  "py" | 
  "pz" | 
  "room" | 
  "sh" | 
  "skybox_ditch_river" | 
  "suzanne" | 
  "suzanne_data"
;


export type OtherAssetPath = 
  "ibls/Harbour_2/m0_nx.rgbm.png" | 
  "ibls/Harbour_2/m0_nx.rgbm.png.webp" | 
  "ibls/Harbour_2/m0_ny.rgbm.png" | 
  "ibls/Harbour_2/m0_ny.rgbm.png.webp" | 
  "ibls/Harbour_2/m0_nz.rgbm.png" | 
  "ibls/Harbour_2/m0_nz.rgbm.png.webp" | 
  "ibls/Harbour_2/m0_px.rgbm.png" | 
  "ibls/Harbour_2/m0_px.rgbm.png.webp" | 
  "ibls/Harbour_2/m0_py.rgbm.png" | 
  "ibls/Harbour_2/m0_py.rgbm.png.webp" | 
  "ibls/Harbour_2/m0_pz.rgbm.png" | 
  "ibls/Harbour_2/m0_pz.rgbm.png.webp" | 
  "ibls/Harbour_2/m1_nx.rgbm.png" | 
  "ibls/Harbour_2/m1_nx.rgbm.png.webp" | 
  "ibls/Harbour_2/m1_ny.rgbm.png" | 
  "ibls/Harbour_2/m1_ny.rgbm.png.webp" | 
  "ibls/Harbour_2/m1_nz.rgbm.png" | 
  "ibls/Harbour_2/m1_nz.rgbm.png.webp" | 
  "ibls/Harbour_2/m1_px.rgbm.png" | 
  "ibls/Harbour_2/m1_px.rgbm.png.webp" | 
  "ibls/Harbour_2/m1_py.rgbm.png" | 
  "ibls/Harbour_2/m1_py.rgbm.png.webp" | 
  "ibls/Harbour_2/m1_pz.rgbm.png" | 
  "ibls/Harbour_2/m1_pz.rgbm.png.webp" | 
  "ibls/Harbour_2/m2_nx.rgbm.png" | 
  "ibls/Harbour_2/m2_nx.rgbm.png.webp" | 
  "ibls/Harbour_2/m2_ny.rgbm.png" | 
  "ibls/Harbour_2/m2_ny.rgbm.png.webp" | 
  "ibls/Harbour_2/m2_nz.rgbm.png" | 
  "ibls/Harbour_2/m2_nz.rgbm.png.webp" | 
  "ibls/Harbour_2/m2_px.rgbm.png" | 
  "ibls/Harbour_2/m2_px.rgbm.png.webp" | 
  "ibls/Harbour_2/m2_py.rgbm.png" | 
  "ibls/Harbour_2/m2_py.rgbm.png.webp" | 
  "ibls/Harbour_2/m2_pz.rgbm.png" | 
  "ibls/Harbour_2/m2_pz.rgbm.png.webp" | 
  "ibls/Harbour_2/m3_nx.rgbm.png" | 
  "ibls/Harbour_2/m3_nx.rgbm.png.webp" | 
  "ibls/Harbour_2/m3_ny.rgbm.png" | 
  "ibls/Harbour_2/m3_ny.rgbm.png.webp" | 
  "ibls/Harbour_2/m3_nz.rgbm.png" | 
  "ibls/Harbour_2/m3_nz.rgbm.png.webp" | 
  "ibls/Harbour_2/m3_px.rgbm.png" | 
  "ibls/Harbour_2/m3_px.rgbm.png.webp" | 
  "ibls/Harbour_2/m3_py.rgbm.png" | 
  "ibls/Harbour_2/m3_py.rgbm.png.webp" | 
  "ibls/Harbour_2/m3_pz.rgbm.png" | 
  "ibls/Harbour_2/m3_pz.rgbm.png.webp" | 
  "ibls/Harbour_2/m4_nx.rgbm.png" | 
  "ibls/Harbour_2/m4_nx.rgbm.png.webp" | 
  "ibls/Harbour_2/m4_ny.rgbm.png" | 
  "ibls/Harbour_2/m4_ny.rgbm.png.webp" | 
  "ibls/Harbour_2/m4_nz.rgbm.png" | 
  "ibls/Harbour_2/m4_nz.rgbm.png.webp" | 
  "ibls/Harbour_2/m4_px.rgbm.png" | 
  "ibls/Harbour_2/m4_px.rgbm.png.webp" | 
  "ibls/Harbour_2/m4_py.rgbm.png" | 
  "ibls/Harbour_2/m4_py.rgbm.png.webp" | 
  "ibls/Harbour_2/m4_pz.rgbm.png" | 
  "ibls/Harbour_2/m4_pz.rgbm.png.webp" | 
  "ibls/Harbour_2/octa.rgbm.png" | 
  "ibls/Harbour_2/octa.rgbm.png.webp" | 
  "ibls/Harbour_2/sh.txt" | 
  "samples/room/env/m0_nx.rgbm.png" | 
  "samples/room/env/m0_nx.rgbm.png.webp" | 
  "samples/room/env/m0_ny.rgbm.png" | 
  "samples/room/env/m0_ny.rgbm.png.webp" | 
  "samples/room/env/m0_nz.rgbm.png" | 
  "samples/room/env/m0_nz.rgbm.png.webp" | 
  "samples/room/env/m0_px.rgbm.png" | 
  "samples/room/env/m0_px.rgbm.png.webp" | 
  "samples/room/env/m0_py.rgbm.png" | 
  "samples/room/env/m0_py.rgbm.png.webp" | 
  "samples/room/env/m0_pz.rgbm.png" | 
  "samples/room/env/m0_pz.rgbm.png.webp" | 
  "samples/room/env/m1_nx.rgbm.png" | 
  "samples/room/env/m1_nx.rgbm.png.webp" | 
  "samples/room/env/m1_ny.rgbm.png" | 
  "samples/room/env/m1_ny.rgbm.png.webp" | 
  "samples/room/env/m1_nz.rgbm.png" | 
  "samples/room/env/m1_nz.rgbm.png.webp" | 
  "samples/room/env/m1_px.rgbm.png" | 
  "samples/room/env/m1_px.rgbm.png.webp" | 
  "samples/room/env/m1_py.rgbm.png" | 
  "samples/room/env/m1_py.rgbm.png.webp" | 
  "samples/room/env/m1_pz.rgbm.png" | 
  "samples/room/env/m1_pz.rgbm.png.webp" | 
  "samples/room/env/m2_nx.rgbm.png" | 
  "samples/room/env/m2_nx.rgbm.png.webp" | 
  "samples/room/env/m2_ny.rgbm.png" | 
  "samples/room/env/m2_ny.rgbm.png.webp" | 
  "samples/room/env/m2_nz.rgbm.png" | 
  "samples/room/env/m2_nz.rgbm.png.webp" | 
  "samples/room/env/m2_px.rgbm.png" | 
  "samples/room/env/m2_px.rgbm.png.webp" | 
  "samples/room/env/m2_py.rgbm.png" | 
  "samples/room/env/m2_py.rgbm.png.webp" | 
  "samples/room/env/m2_pz.rgbm.png" | 
  "samples/room/env/m2_pz.rgbm.png.webp" | 
  "samples/room/env/m3_nx.rgbm.png" | 
  "samples/room/env/m3_nx.rgbm.png.webp" | 
  "samples/room/env/m3_ny.rgbm.png" | 
  "samples/room/env/m3_ny.rgbm.png.webp" | 
  "samples/room/env/m3_nz.rgbm.png" | 
  "samples/room/env/m3_nz.rgbm.png.webp" | 
  "samples/room/env/m3_px.rgbm.png" | 
  "samples/room/env/m3_px.rgbm.png.webp" | 
  "samples/room/env/m3_py.rgbm.png" | 
  "samples/room/env/m3_py.rgbm.png.webp" | 
  "samples/room/env/m3_pz.rgbm.png" | 
  "samples/room/env/m3_pz.rgbm.png.webp" | 
  "samples/room/env/m4_nx.rgbm.png" | 
  "samples/room/env/m4_nx.rgbm.png.webp" | 
  "samples/room/env/m4_ny.rgbm.png" | 
  "samples/room/env/m4_ny.rgbm.png.webp" | 
  "samples/room/env/m4_nz.rgbm.png" | 
  "samples/room/env/m4_nz.rgbm.png.webp" | 
  "samples/room/env/m4_px.rgbm.png" | 
  "samples/room/env/m4_px.rgbm.png.webp" | 
  "samples/room/env/m4_py.rgbm.png" | 
  "samples/room/env/m4_py.rgbm.png.webp" | 
  "samples/room/env/m4_pz.rgbm.png" | 
  "samples/room/env/m4_pz.rgbm.png.webp" | 
  "samples/room/env/octa.rgbm.png" | 
  "samples/room/env/octa.rgbm.png.webp" | 
  "samples/room/env/sh.txt" | 
  "samples/room/room.glb" | 
  "samples/suzanne/suzanne_data.bin" | 
  "samples/suzanne/suzanne.gltf" | 
  "samples/textures/protospace/cubemap.astc.ktx" | 
  "samples/textures/protospace/cubemap.dxt.ktx" | 
  "samples/textures/protospace/cubemap.etc.ktx" | 
  "samples/textures/protospace/cubemap.pvr.ktx" | 
  "samples/textures/protospace/nx.webp" | 
  "samples/textures/protospace/ny.webp" | 
  "samples/textures/protospace/nz.webp" | 
  "samples/textures/protospace/px.webp" | 
  "samples/textures/protospace/py.webp" | 
  "samples/textures/protospace/pz.webp" | 
  "samples/textures/skybox_ditch_river.webp"
;


export type AssetName = TextureName | OtherAssetName;
export type AssetPath = TexturePath | OtherAssetPath;
